### ISSUE TITLE
Versions on npm do not reflect git tags in this repository

### ISSUE THREAD

**Issue by adzialocha** [CirclesUBI/circles-contracts#123] opened 2021-03-04 17:04 UTC

**Comment by ana0** [comment] 2021-03-04 17:06
Pretty sure this a duplicate of #118

**Closed** 2021-03-04 17:10 UTC
Labels: confusion :confused:

**Comment by adzialocha** [comment] 2021-03-04 17:11
@ana0 Thanks, I will close this and move over to the other one.

Also I realized on npm it says "Do not use this on production" :smile_cat:
